# Generated by Django 5.0.4 on 2024-04-12 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kominiarz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=20)),
                ('nazwisko', models.CharField(max_length=20)),
                ('wiek', models.IntegerField()),
                ('opis', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Zamowienie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miasto', models.CharField(max_length=20)),
                ('ulica', models.CharField(max_length=20)),
                ('numerdomu', models.IntegerField()),
                ('numermieszkania', models.IntegerField()),
                ('dzien', models.DateField()),
                ('kominiarz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kominiarzapp.kominiarz')),
            ],
        ),
    ]
